apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo-service
  name: dso-demo-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30003
  selector:
    app: dso-demo
  type: NodePort
status:
  loadBalancer: {}

